function [r] = Pulaski_I_02_f01(o0, ttm_offs, dvm, Nm1, Nm2, mu_K, A, T, da1, da2)

    [os, ths] = applyMultipleManoeuvres(o0, T + ttm_offs(1, 1:(Nm1 + Nm2)), ...
                dvm(1, 1:(Nm1 + Nm2)), (A * ones(1, (Nm1 + Nm2)) + da1), ...
                zeros(1, (Nm1 + Nm2)) + da2, mu_K);
    ths(2, (Nm1 + Nm2 + 1)) = timeToArg(ttm_offs(1, (Nm1 + Nm2 + 1)), ...
            os(1, (Nm1 + Nm2 + 1)).p, os(1, (Nm1 + Nm2 + 1)).e, mu_K, ...
            os(1, (Nm1 + Nm2 + 1)).peT);
    [x, v] = paramsToPosVel(ths(2, (Nm1 + Nm2 + 1)), ...
               os(1, (Nm1 + Nm2 + 1)).p, os(1, (Nm1 + Nm2 + 1)).e, ...
               os(1, (Nm1 + Nm2 + 1)).lan, os(1, (Nm1 + Nm2 + 1)).incl, ...
               os(1, (Nm1 + Nm2 + 1)).aop, mu_K);
    r = [x; v];

end