function [H] = Pulaski_I_03_Hessian(cf, a, da)
    N = size(a, 2);
    g = zeros(N, N);
    for idx_1 = 1:N
            q = zeros(1, N);
            q(1, idx_1) = da;
            H(idx_1, idx_1) = (cf(a(1, 2:end) + q(1, 2:end), ...
                               382 * (a(1, 1) + q(1, 1))) - ...
                               2 * cf(a(1, 2:end), 382 * (a(1, 1))) + ...
                               cf(a(1, 2:end) - q(1, 2:end), ...
                               382 * (a(1, 1) - q(1, 1)))) / (da ^ 2);

        for idx_2 = (idx_1 + 1):N

            q1 = zeros(1, N);
            q2 = zeros(1, N);
            q1(1, idx_1) = da;
            q2(1, idx_2) = da;
            H(idx_1, idx_2) = (cf(a(1, 2:end) + q1(1, 2:end) + q2(1, 2:end), ...
                             382 * (a(1, 1) + q1(1, 1) + q2(1, 1))) ...
                             - cf(a(1, 2:end) - q1(1, 2:end) + q2(1, 2:end), ...
                             382 * (a(1, 1) - q1(1, 1) + q2(1, 1))) ...
                             - cf(a(1, 2:end) + q1(1, 2:end) - q2(1, 2:end), ...
                             382 * (a(1, 1) + q1(1, 1) - q2(1, 1))) ...
                             + cf(a(1, 2:end) - q1(1, 2:end) - q2(1, 2:end), ...
                             382 * (a(1, 1) - q1(1, 1) - q2(1, 1)))) / (4 * da ^ 2);
            H(idx_2, idx_1) = H(idx_1, idx_2);
        end

    end

end